language: java
jdk: oraclejdk8

# Define the services to use
services:
  - docker

before_install:
  - sudo service mysql stop
  - docker pull takimatraining/devops-training-db
  - docker run -d -p 127.0.0.1:3306:3306 takimatraining/devops-training-db

# Run Unit Test and Integration Tests
script:
  - mvn verify
  - |
    mvn clean install sonar:sonar \
    -Dsonar.projectKey=PierreBer_sample-application-students \
    -Dsonar.organization=pierreber-github \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=0c3821a2c1785a6bf50af5003f3eb279f4b63a5c

# Cache the .m2 folder to prevent redownloading dependencies on each build
cache:
  directories:
  - "$HOME/.m2/repository"

# Send an email to the commiter if the pipeline failed at some point
notifications:
  email:
    on_failure: always

env:
  global:
    - secure: "k65RtADSjHNgZ+RvsolR67x0D/XXjhQcDbYe93180tD5m2XBFpLYvkZZ6/aizCjRSiFJC1kuAtezzoJLAZS+kZpTIio2+1yJXOhnTJi2vqiN6HnwMfAVx1ugaxC1TPquBu+FUJSMVDKxxIeAzdMYN4ckQrSC+iSXp/UJD0mmx46SRROOkg+KZAHeSwMDaWeRUhwlXwKdyyDGM+kOCzpn/VZOkN8nkVDYTAyXZu7r4sC9eHodmDE5ZmytQqxbQ6LLQYcG/xzkXj+9fxquFq69PmakFr9L88YGZ+K6oytGcvxXLgYweSFtUVMRg+176u94iZqa/KPVlBPHaCMMCbKW+0pxX3GheKijPY+DZzeUqebfNXE4F7RGhGOreb4L8pMeFtKfiYs0i5pScZ3/d7Qz5fnMXR7vZ//8z2ZY4aor9a5vSCYJTs6k/Pwijsis3VkUUOAMyEXTwII43/BgP5F1lrcPX61ydQqflM43j+qoSgMaRljVkcxWRaH4fAUqW5RgoaJHO4YWvYC56pxHWWXvgxL2ce+/HCIFp+A147ISJR0B2N6Z8eZLvO4CYho0Pti4GWKOn44YtGh+oMMueu/vDk/16wRRY3RB1Jt7vkYakIq+Us57AAJuJiWHMspHQVhu71b8N4hfZ7I+UU41V6M94KY9WFdD0/5lAzEDM1gwbEk="
  